Task3
OlegMazurenko/altexsoft-lab-2021 pull request #3
Opened 2021-04-21 15:37 UTC by OlegMazurenko

2021-04-26 21:25 UTC, OlegMazurenko commented
Ready to review @serhii-shkodenko

2021-04-27 01:59 UTC, serhii-shkodenko requested changes

2021-04-27 01:59 UTC, serhii-shkodenko commented on DeliveryService/Data/StoreContext.cs
> +    class StoreContext : IStoreContext
Не хватает модификатора доступа.

2021-04-27 01:59 UTC, serhii-shkodenko commented on DeliveryService/Presenter.cs
> +                try
Блок try здесь лишний. Вполне достаточно switch statement.

2021-04-27 11:11 UTC, serhii-shkodenko requested changes
Кажется, все хорошо. Поправь только одно замечание и если больше ничего не найду, будет аппрув.

2021-04-27 11:11 UTC, serhii-shkodenko commented on DeliveryService/Presenter.cs
> +        public void ShowMenu(IProductController productController)
Логичнее будет сделать конструктор, в котором попросить объект `IProductController`, сохранить его в приватное поле и и использовать внутри этого метода. Тогда ты избавишься от необходимости постоянно прокидывать в параметры метода этот объект. Остальные методы этого класса лучше переписать тогда тоже от этого избавятся.

2021-04-27 11:44 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-04-27 11:45 UTC, merged