Task4
OlegMazurenko/altexsoft-lab-2021 pull request #4
Opened 2021-04-30 23:58 UTC by OlegMazurenko

2021-05-02 00:36 UTC, serhii-shkodenko requested changes

2021-05-02 00:36 UTC, serhii-shkodenko commented on DeliveryService/Controllers/ProductController.cs
> +            product.Id = storeContext.Products.Count > 0 ? storeContext.Products[storeContext.Products.Count - 1].Id + 1 : 0;
Здесь есть дав момента. 
Id принято начинать с 1. 
Эта логика будет будет провоцировать появление элементов с одинаковыми `Id`, например, вследствие  удаления элементов в коллекции. Чтобы этого не происходило, нужно находить максимальный `Id` среди элементов и прибавлять к нему единицу.

2021-05-02 00:36 UTC, serhii-shkodenko commented on DeliveryService/Controllers/ProductController.cs
>          public void CreateProduct(Product product)
Этот метод уже не создает продукт, а только устанавливает его `Id`. Это стоит отобразить в его имени.

2021-05-04 20:50 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, эти мелочи и будет апрув.

2021-05-04 20:50 UTC, serhii-shkodenko commented on DeliveryService/Extensions/Extensions.cs
> +            var pattern = @"^ул(ица\s|[.][\s]?){1}[А-Яа-я]{5}[А-Яа-я\s]*[.,]{1}[\s]?д(ом|[.]){1}[\s]?[0-9]{1,3}(,[\s]?кв(артира|[.]){1}[\s]?[0-9]{1,3})?$";
Не все улицы проходят проверку. Поправь, пожалуйста. 
![not_all](https://user-images.githubusercontent.com/69808191/117067762-1740eb80-ad33-11eb-8daf-04381726e440.jpg)

2021-05-04 20:50 UTC, serhii-shkodenko commented on DeliveryService/Controllers/OrderController.cs
> +    class OrderController : IOrderController
Забыл модификатор доступа.

2021-05-04 20:58 UTC, OlegMazurenko commented on DeliveryService/Extensions/Extensions.cs
> +            var pattern = @"^ул(ица\s|[.][\s]?){1}[А-Яа-я]{5}[А-Яа-я\s]*[.,]{1}[\s]?д(ом|[.]){1}[\s]?[0-9]{1,3}(,[\s]?кв(артира|[.]){1}[\s]?[0-9]{1,3})?$";
Адрес с номером квартиры 8999 не проходил, так как максимальное значение для квартиры было трехзначным. Поменял на четырехзначное.

2021-05-04 21:08 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-05-04 21:09 UTC, merged