Task5
OlegMazurenko/altexsoft-lab-2021 pull request #5
Opened 2021-05-13 15:14 UTC by OlegMazurenko

Добавил логгер и систему авторизации.

2021-05-18 00:18 UTC, serhii-shkodenko requested changes

2021-05-18 00:18 UTC, serhii-shkodenko commented on DeliveryService/Models/User.cs
> +        public string AccessLevel { get; set; }
Это свойство лучше сдедать `enum`. Поскольку у тебя будет заранее определенный список уровней доступа, ты избежишь ошибок, связанных с написанием строк в качестве значений.

2021-05-18 13:47 UTC, OlegMazurenko commented on DeliveryService/Models/User.cs
> +        public string AccessLevel { get; set; }
Переделал. Раньше никогда не использовал enum, надеюсь сделал правильно.

2021-05-20 22:36 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-05-20 22:43 UTC, merged