Task8
OlegMazurenko/altexsoft-lab-2021 pull request #8
Opened 2021-06-10 18:43 UTC by OlegMazurenko

2021-06-14 14:20 UTC, serhii-shkodenko requested changes

2021-06-14 14:20 UTC, serhii-shkodenko commented on DeliveryService/Controllers/CurrencyController.cs
> +            decimal.TryParse(rate.Replace('.', ','), out var parsedRate);
А разве с культурой распарсить не получается?

2021-06-14 14:20 UTC, serhii-shkodenko commented on DeliveryService/Presenter.cs
> +        public Presenter(IProductController productController, IUserController userController, IOrderController orderController, ICurrencyController currencyController)
Я бы вынес эту зафисимость в бизнес слой, задача UI только показать конечный результат.

2021-06-14 14:20 UTC, serhii-shkodenko commented on DeliveryService/Program.cs
> +        static async Task Main(string[] args)
Добавь еще сюда модификатор доступа.

2021-06-14 14:20 UTC, serhii-shkodenko commented on DeliveryService/Program.cs
>      class Program
Добавь еще сюда модификатор доступа.

2021-06-14 17:54 UTC, OlegMazurenko commented on DeliveryService/Program.cs
> +        static async Task Main(string[] args)
А какой нужно ставить модификатор доступа для Main и Program?

2021-06-14 19:19 UTC, OlegMazurenko commented on DeliveryService/Program.cs
> +        static async Task Main(string[] args)
Поставил для Main и Program их модификаторы доступа по умолчанию.

2021-07-10 22:42 UTC, serhii-shkodenko requested changes

2021-07-10 22:42 UTC, serhii-shkodenko commented on DeliveryService/Controllers/CurrencyController.cs
> +        public async Task<decimal> ConvertToUsdAsync(decimal price)
Этот метод занимается сразу двумя вещами:
1. Обращается на внешний сервис за данными.
2. Парсит их (в достаточно неоптимальной манере. Лучше было бы сделать модель и десериализовывать полученный Json).
3. Осуществляет конвертацию цены одно валюты в другую.
Это нарушение Single Responsibility principle. Постарайся вынести хотя бы конвертацию валют в другое место, потому что этот код относится к бизнес-слою и ему точно не место здесь.

2021-08-23 08:20 UTC, serhii-shkodenko requested changes

2021-08-23 08:20 UTC, serhii-shkodenko commented on DeliveryService/Controllers/CurrencyController.cs
> +            var rate = response
Единственное замечение: реализация сервиса для получаения курса валют. Полученные от сервера данные в виде валидного JSON десериализовывают, а не вытаскивают из него данные с помощью строковых операций. Тебе нужно из полученного JSON сгенерировать классы и десериализовать в них твои данные. А наверху твоего стека вызовов ты будешь работать уже с объектами. Добавь, пожлуйста, десериализацию и можно будет мержить.

2021-08-28 15:38 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-08-28 15:45 UTC, merged